version: "3.7"

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql-opeek
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: opeek
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    volumes:
      - /opeek/mysql:/var/lib/mysql
    networks:
      - java_network
  obus-boot:
    container_name: obus-boot
    image: obushakim/demo-jenkins-boot:1.0.0
    ports:
      - 9090:9090
    depends_on:
      - db
    environment:
      NAME: Docker
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    networks:
      - java_network
networks:
  java_network:
    name: java_network 